### ISSUE TITLE
動画が開けない

### ISSUE THREAD

**Issue by KimidoriBoushi3** [mrtska/SRNicoNico#197]
理由はわからないが、動画（だいたい全部）を開くだけで※１のエラーを吐いて堕ちるようになりました。

本日PCを起動し、いつものように視聴しようと思ったところこうなりました。
直前にPCのアップデートなどは行われておりません。

PC自体の再起動と、NiconicoViewerの再インストールを試しましたが変化なし。

PCスペックは※２を参照ください。

※１
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
   at SRNicoNico.Services.NicoNicoSessionService.PostAsync(String url, String json, IDictionary`2 additionalHeaders)
   at SRNicoNico.Services.NicoNicoVideoService.GetCommentAsync(WatchApiDataComment comment)
   at SRNicoNico.ViewModels.VideoCommentViewModel.Initialize(WatchApiDataComment apiData)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at SRNicoNico.App.Main()

※２
------------------
System Information
------------------
      Time of this report: 11/29/2023, 14:22:39
             Machine name: DESKTOP-HTFAHG7
               Machine Id: Unknown
         Operating System: Windows 11 Home 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
                 Language: Japanese (Regional Setting: Japanese)
      System Manufacturer: ASUS
             System Model: System Product Name
                     BIOS: 2407 (type: UEFI)
                Processor: AMD Ryzen 7 5800X 8-Core Processor              (16 CPUs), ~3.8GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32654MB RAM
                Page File: 27696MB used, 37726MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.4.7
           DxDiag Version: 10.00.22621.0001 32bit Unicode

**Comment by KimidoriBoushi3** [comment]
と思ったらTwitterでご存知であることを今頃知りました。
すいません。

**Comment by mrtska** [comment]
https://github.com/mrtska/SRNicoNico/pull/196
修正済みではあるのでアップデートが配信されるまでお待ちいただければと🙏

**Comment by KimidoriBoushi3** [comment]
了解しました。
一日千秋の思いでお待ちしております。
